/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Classes;

import tx.utilitarios.TXProperties;

/**
 *
 * @author Taffrel Xavier <taffarel_deus@hotmail.com>
 */
public class ConfigIniPHP {

    public static String criarArquivoDeConfiguracao() {
        return "﻿<?php\n"
                + "//===============================================================+\n"
                + "//==============ARQUIVO DE CONFIGURAÇÃO DO SISTEMA===============|\n"
                + "//===============================================================+\n"
                + "//===============================================================+\n"
                + "//                      CONFIGURAÇÕES GLOBAIS                    |\n"
                + "//===============================================================+\n"
                + "//Define a timezone para Araguaina\n"
                + "date_default_timezone_set('America/Araguaina');\n"
                + "\n"
                + "/* A versão 1.0 indica que é a última versão válida. */\n"
                + "define('VERSAO_EVTX_SYSTEM', '0.1');\n"
                + "/* Nome da Empresa desenvolvedora */\n"
                + "define('DESENVOLVEDOR', '');\n"
                + "/* Url do sítio da empresa desenvolvedora */\n"
                + "define('DESENVOLVEDOR_URL', '');\n"
                + "\n"
                + "define('_SERVIDOR_', $_SERVER['HTTP_HOST']);\n"
                + "\n"
                + "define('SERVER_NOME', $_SERVER['SERVER_NAME']);\n"
                + "\n"
                + "define('NEO_DOCUMENT_ROOT', $_SERVER['DOCUMENT_ROOT']);\n"
                + "\n"
                + "//Temporiamente...\n"
                + "if (SERVER_NOME == 'ltai-edu-br.umbler.net') {\n"
                + "    header('location: //' . _SERVIDOR_ . '/' . NEO_HOSTNAME . '/login');\n"
                + "}\n"
                + "\n"
                + "//Configurações da parte de Desenvolvimento\n"
                + "switch ($_SERVER['SERVER_NAME']) {\n"
                + "    case 'localhost':\n"
                + "        define('_DOMINIO_', 'http://localhost/' . NEO_HOSTNAME . '/');\n"
                + "        break;\n"
                + "    case 'ava':\n"
                + "        define('_DOMINIO_', 'http://ava/' . NEO_HOSTNAME . '/');\n"
                + "        break;\n"
                + "    case _SERVIDOR_: //Nome do servidor\n"
                + "        define('_DOMINIO_', '//' . _SERVIDOR_ . '/' . NEO_HOSTNAME . '/');\n"
                + "        break;\n"
                + "    default : //Nome do servidor\n"
                + "        define('_DOMINIO_', '//' . SERVER_NOME . DIRECTORY_SEPARATOR);\n"
                + "        break;\n"
                + "}\n"
                + "\n"
                + "//===============================================================+\n"
                + "//                  CONFIGURAÇÕES DE PÁGINAS                     |\n"
                + "//===============================================================+\n"
                + "\n"
                + "define('CONTATO_WHATSAPP', '63999948823');\n"
                + "\n"
                + "//===============================================================+\n"
                + "//                 CONFIGURAÇÕES DE SEGURANÇA                   |\n"
                + "//===============================================================+\n"
                + "\n"
                + "define('_BR_', '<br/>');\n"
                + "\n"
                + "//Para segurança do Sistema\n"
                + "define('KEY_SECURITY', '1cc6TuGPAASdN0/Ot++kffHkgkU/S8kPkVDE8mw6xT0=');\n"
                + "\n"
                + "define('NEO_WRITE_FILE_HTACCES', $_SERVER['DOCUMENT_ROOT']);\n"
                + "\n"
                + "/* O ID do Administrador | Não permite algumas funções nestes IDs, como por exemplo, desativá-los. */\n"
                + "\n"
                + "$IDS_DEFINE_ARRAY = array(36, 59, 58);\n"
                + "\n"
                + "//===============================================================+\n"
                + "//                 CONFIGURAÇÕES DO BANCO DE DADOS               |\n"
                + "//===============================================================+\n"
                + "switch (SERVER_NOME) {\n"
                + "    case 'localhost':\n"
                + "        /** MySQL hostname */\n"
                + "        define('DB_HOST', 'localhost');\n"
                + "        /** MySQL database username */\n"
                + "        define('DB_USER', '" + TXProperties.getProp("user.name") + "');\n"
                + "        /** The name of the database for WordPress */\n"
                + "        define('DB_NAME', '" + TXProperties.getProp("db.name") + "');\n"
                + "        /** MySQL database password */\n"
                + "        define('DB_PASSWORD', '" + TXProperties.getProp("senha") + "');\n"
                + "        break;\n"
                + "    case 'rsvtelecom.com.br':\n"
                + "        define('DB_HOST', '');\n"
                + "        /** MySQL database username */\n"
                + "        define('DB_USER', '');\n"
                + "        /** The name of the database for WordPress */\n"
                + "        define('DB_NAME', '');\n"
                + "        /** MySQL database password */\n"
                + "        define('DB_PASSWORD', '');\n"
                + "        break;\n"
                + "}\n"
                + "\n"
                + "if (class_exists('Conexao')) {\n"
                + "\n"
                + "//===============================================================+\n"
                + "//                 CONFIGURAÇÕES DE CONEXÃO                      |\n"
                + "//===============================================================+\n"
                + "\n"
                + "    $connection = Conexao::conn();\n"
                + "} else {\n"
                + "    header('location:../');\n"
                + "}";
    }
}
